### ISSUE TITLE
make sure to comment main parts of code 

### ISSUE THREAD

**Issue by ad3429** [roadrunner-75/tea-cozy#2]
https://github.com/roadrunner-75/tea-cozy/blob/master/index.html#L1-L91

Make sure to comment the main parts of your HTML in future projects. This becomes increasingly important as your projects become larger and more complex. Here is a quick refresher on commenting in HTML:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/31856290-3eed43ec-b68b-11e7-9161-dce5efebd9d8.png">

**Comment by roadrunner-75** [comment]
Great tip. I'll start doing it, as projects become more complex and it gets harder to remember how I organized the code. And it also helps anybody who also code the page. Thanks a lot!
