### ISSUE TITLE
CSS is clean and succinct 

### ISSUE THREAD

**Issue by ad3429** [roadrunner-75/tea-cozy#3]
https://github.com/roadrunner-75/tea-cozy/blob/master/css/style.css#L1-L107

Your CSS is short, clean and succinct -- make sure to keep it up! One area of improvement is to make sure to comment your main stylings so that it's absolutely clear why you are styling elements a particular way. Here is a quick reminder on commenting in CSS:

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/31856293-539ba69e-b68b-11e7-80bd-2c153181048d.png">

**Comment by roadrunner-75** [comment]
I'll use it as a best practice. Thank you!
