### ISSUE TITLE
responsive design

### ISSUE THREAD

**Issue by ad3429** [roadrunner-75/tea-cozy#4]
In the next project you will learn more about responsive design, which is basically web design that lets you create content that fits different browser sizes/platforms. Here is a great resource to get you to start thinking about that:

https://www.w3schools.com/css/css_responsive_intro.asp

**Comment by roadrunner-75** [comment]
Thank you! In the project, when I had to study the final code to try to understand the solutions used, I noticed thwy would not work the same way on smartphones. Great to advance one more step. Thanks for the material!
